version: "3.9"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Surveyhubtrue
      MYSQL_DATABASE: svh_db
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80